### PR TITLE
Feat 62 save config

### LINKED ISSUE #62: Save config
**Is your feature request related to a problem? Please describe.**
Config is not being save at end of scan 

**Describe the solution you'd like**
Acquisition and instrument config yaml should be saved at end of scan 

**Acceptance Criteria**
- [ ] Add function in acquisition.py and instrument.py that saves corresponding config

### PR DESCRIPTION
**Pull request by micahwoodard**
fixes #62 
- created updating and saving config function in acquisition and instrument yaml
-  pass in yaml handler are argument

### CODE REVIEW

**Comment by micahwoodard** [comment]
@adamkglaser do you think having the yaml handeler as an init arg? I originally had it hard coded in the acquisition init, but thought making it an argument allowed users to customize it for their particular needs and inputs. It might be nice to somehow imbed this in the config yamls themselves? Maybe not a priority right now but just an idea

**Comment by adamkglaser** [comment]
@micahwoodard this sounds good to me, but I'm not super familiar with YAML/handlers. what is the handler doing and what would be other options? but all of these PRs look OK to me.

one quick question is how the saving is done. if i understand correctly, the local init YAML files are left untouched, and updated only when closing the UI via the pop up dialogue box? but the experiment specific YAML files are saved directly to the final directory (external if transferring is activated otherwise local). if this is the case, when do these new YAML files get saved, at the start of an acquisition - or at the end?

**Comment by micahwoodard** [comment]
The handler is just dictating how variables like numpy.float64 or Path are parsed and saved within the config.yaml. yaml.dump can't save objects, so you have to use a handler to deal with saving objects correctly.  Other options would be to make it a rule that variable being saved must not be objects, but it's a little annoying and limiting. 

Yeah local versions can be updated or be saved in another location by user when UI is closed. The user can also leave local versions unupdated if they would like. 

And then the acquisition engine will save the configs [at the end of a scan](https://github.com/AllenNeuralDynamics/exaspim-control/blob/2192b78be85a132e8436bf100c0c4a713b530903/exaspim_control/exa_spim_acquisition.py#L241C8-L252C123) at relevant places. It could happen at the beginning, and then we could have it happen within the voxel repo. I don't really have a good reason why it should happen at the end rather than at the beginning

**Comment by adamkglaser** [comment]
Got it thanks that all makes sense. You are a YAML master now. I think it is fine at the end, and outside of voxel, the only thought that came to mind is if things crash there is no record of what the acquisition was. But maybe we could account for that by doing a try/except in the acquisition engine? Otherwise this is good to me.

**Review by adamkglaser — APPROVED** [review]

**Comment by micahwoodard** [comment]
Okay try/finally sounds good to me. I already merged the exaspim-control branch, but I'm working on a metadata-saving branch so I will implement the try finally in there. Hopefully I'll have metadata done by end of day.

**Pull request merged**
