### PR TITLE
Update metadata

### PR DESCRIPTION
**Pull request by micahwoodard**
- update laser drivers to include wavelength property
- update acquisition yaml to align with aind-data-schema nomenclature

### CODE REVIEW

**Comment by micahwoodard** [comment]
needs to be merged in with metadata changes for exaspim

**Review by adamkglaser — CHANGES_REQUESTED** [review]
@micahwoodard this all looks good to me. However for the metadata class, I realize now that some of the specifics (anatomical orientation especially) are very AIND / exaspim specific. Would it make sense to move these into an "exaspim_metadata" class in exaspim-control that subclasses the metadata_class instead?

**Comment by micahwoodard** [comment]
okay @adamkglaser I've removed aind specific metadata variables from metadata class

**Comment by adamkglaser** [comment]
@micahwoodard  OK I am ok with merging this now.

**Pull request merged**
