### PR TITLE
Deliminated property

### PR DESCRIPTION
**Pull request by micahwoodard**
Added Deliminatedproperty decorators to applicable properties, mainly in camera and laser class. Had to refactor roi in camera class. Should work but some cameras I was unfamiliar with so may need to retest

### CODE REVIEW

**Comment by adamkglaser** [comment]
Your implementation and edits look good to me. Some forward looking and also clarifying questions:

- Do we want to handle units in the DelineatedProperty as well? If so add that later down the road?
- Any of the device properties that are dict based are already bounded by the keys in the dict?
- We can take care of it later, but we should probably go through the existing devices and change any of the non dict properties to also use this new decorator. For example stage speed, stage acceleration, etc. When possible, we should try to auto-populate the min/max/step values from the driver. But when not possible, we add hard-coded values at the top of the device driver file in all caps?

**Comment by micahwoodard** [comment]
- Yes on units. Just haven't had a chance to implement. Will be very easy though
- I don't know what that means exactly? I couldn't figure out a way to make the values in a dictionary each be a Deliminatedproperty if that is the question. Probably doable or we may need to create a separate descriptor to handle this. 
- Yes I agree. I tried to go through the asi driver, but since it is mostly just functions and not properties, it would be a little tricky/code breaking refactor

**Comment by adamkglaser** [comment]
- Sounds good was just checking. This sounds good.
- I should have been more specific. I meant the dict keys don't need this and are already limited by whatever keys are in the dict. This new wrapper helps enforce bounded behavior for non dict properties. 
- Yeah no rush on this, just make sure I had a mental note of it as a future TO DO.

I am ok with merging

**Review by adamkglaser — APPROVED** [review]

**Comment by micahwoodard** [comment]
Yay great! I've put these todo's as issues and in the project board so we can get to them in the future

**Pull request merged**
